// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use hardcoded values for development, these will be replaced by environment variables in production
const SUPABASE_URL = 'https://mfkjsmvcaytwiukxahqj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_KO0eSsqdbiEylvjiCMOkQA_N84fIL1i';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
